# Generated by Django 4.0.1 on 2023-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketRelay', '0002_pushnotificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='feedback_received_by_CE',
            field=models.BooleanField(default=False),
        ),
    ]
