# Generated by Django 3.1 on 2023-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketRelay', '0006_ticket_ticket_action_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delivery_method',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
